version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run sls -- deploy -s $STAGE -r $REGION
  post_build:
    commands:
      - npm run test
      - npm run acceptance